fixtures:
  repositories:
    chocoinst: "https://github.com/AdvancedLearning/advlearning-chocoinst"
    awscli:
      repo: "https://github.com/AdvancedLearning/advlearning-awscli"
      branch: "develop"
  forge_modules:
    stdlib: "puppetlabs/stdlib"
    inifile: "puppetlabs/inifile"
    registry: "puppetlabs/registry"
    chocolatey: "chocolatey/chocolatey"
  symlinks:
    adv_windows: "#{source_dir}"
