fixtures:
  repositories:
    windows_disable_ipv6: git://github.com/martezr/puppet-windows_disable_ipv6.git
    chocolatey_sw: https://github.com/CERIT-SC/puppet-chocolatey_sw.git
    chocolatey: https://github.com/rismoney/puppet-chocolatey.git
  forge_modules:
    stdlib: "puppetlabs/stdlib"
    inifile: "puppetlabs/inifile"
    dism: "puppetlabs/dism"
    registry: "puppetlabs/registry"
  symlinks:
    adv_windows: "#{source_dir}"
