fixtures:
  repositories:
  forge_modules:
    stdlib: "puppetlabs/stdlib"
    inifile: "puppetlabs/inifile"
    dism: "puppetlabs/dism"
    registry: "puppetlabs/registry"
    chocolatey: "chocolatey/chocolatey"
  symlinks:
    adv_windows: "#{source_dir}"
