fixtures:
  repositories:
    chocolatey_sw: https://github.com/CERIT-SC/puppet-chocolatey_sw.git
    windows_disable_ipv6: https://github.com/AdvancedLearning/puppet-windows_disable_ipv6.git
  forge_modules:
    stdlib: "puppetlabs/stdlib"
    inifile: "puppetlabs/inifile"
    dism: "puppetlabs/dism"
    registry: "puppetlabs/registry"
    chocolatey: "rismoney/chocolatey"
  symlinks:
    adv_windows: "#{source_dir}"
