fixtures:
  repositories:
    stdlib: git://github.com/puppetlabs/puppetlabs-stdlib.git
    initfile: git://github.com/puppetlabs/puppetlabs-inifile.git
    dism: git://github.com/puppetlabs/puppetlabs-dism.git
    registry: git://github.com/puppetlabs/puppetlabs-registry.git
    windows_disable_ipv6: git://github.com/martezr/puppet-windows_disable_ipv6.git
    chocolatey_sw: https://github.com/CERIT-SC/puppet-chocolatey_sw.git
    chocolatey: https://github.com/rismoney/puppet-chocolatey.git
  symlinks:
    adv_windows: "#{source_dir}"
