env:
  - PUPPET_VERSION=3.3.2
  - PUPPET_VERSION=3.7.3
notifications:
  email: false
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
bundler_args: ''
script: 'bundle exec rake lint && SPEC_OPTS="--format documentation" bundle exec rake spec'
gemfile: Gemfile
